version: '3.8'

services:
  backend:
    container_name: mern-boiler-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - imraffy-network

  frontend:
    container_name: mern-boiler-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    networks:
      - imraffy-network

networks:
  imraffy-network:
    external: true
